# Generated by Django 3.0 on 2022-10-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppy',
            name='picture',
        ),
    ]
